"""Compatibility 4.0 -> 4.1 (architecture §1.23, C-23): nothing that passed under 4.0 fails under 4.1.

The only difference between the 4.0 and the 4.1 release lines is the Wave 3 rows of ``check-modes.json`` (the Wave 2
rows keep their 4.0 values, L-47). This suite replays:

- every legacy ``spec.json`` / ``project.json`` fixture through ``validate --strict`` under the 4.0 and the 4.1 line:
  a fixture that passes under 4.0 must pass under 4.1, and no error code may appear that 4.0 did not report;
- the linter over the good fixture project under the 4.1 line;
- the guard tables: ``compat.json`` carries, for every Wave 2 compat case with a ``project.json``, a ``compat41-``
  case whose ``checks`` add every Wave 3 row at its 4.1 default (``run_tables.py --only compat``). The table must
  equal ``wave3_cases()``; regenerate it with ``python3 test_compat_w3.py --write`` when a compat case is added.

@req REQ-W3-062
"""
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import _path

STATE = _path.SCRIPTS_DIR / "karvey-state.py"
LEGACY = _path.FIXTURES_DIR / "legacy"
TABLE = _path.TESTS_DIR / "hooks" / "tables" / "compat.json"
PREFIX_W2, PREFIX_W3 = "compat-", "compat41-"
LINE_VERSION = {"4.0": "4.0.0", "4.1": "4.1.0"}
W3_NOTE = (" wave3-optimization E1.F11.T3 / REQ-W3-062: each compat41- case replays the compat- case of the same "
           "name with every Wave 3 check-modes row added to project.json checks at its 4.1 default (sponsor.leak and "
           "loadlist.missing blocking); generated by tests/unit/test_compat_w3.py --write.")

RUNNER = """
import runpy, sys
sys.path.insert(0, sys.argv[1])
import karvey_lib.modes as m
m.__version__ = sys.argv[2]
sys.argv = [sys.argv[3]] + sys.argv[4:]
runpy.run_path(sys.argv[0], run_name="__main__")
"""


def run_on_line(line, script, *argv, cwd=None):
    """``(exit, envelope)`` of a plugin script run with the release line pinned (``modes.__version__``)."""
    cmd = [sys.executable, "-c", RUNNER, str(_path.SCRIPTS_DIR), LINE_VERSION[line], str(script)] + list(argv)
    cp = subprocess.run(cmd, capture_output=True, text=True, timeout=120, cwd=cwd)
    try:
        env = json.loads(cp.stdout.strip().splitlines()[-1])
    except (ValueError, IndexError):
        env = {"errors": [{"code": "no-json", "message": cp.stderr.strip()[-300:]}]}
    return cp.returncode, env


def wave3_defaults():
    reg = json.loads((_path.SCHEMAS_DIR / "check-modes.json").read_text(encoding="utf-8"))
    return {c["id"]: c["defaults"]["4.1"] for c in reg["checks"] if set(c["defaults"]) == {"4.1"}}


def wave3_cases(cases):
    """The ``compat41-`` replays of the Wave 2 compat cases that carry a ``project.json``."""
    extra = wave3_defaults()
    out = []
    for c in cases:
        if not c["id"].startswith(PREFIX_W2):
            continue
        repo = c.get("given", {}).get("repo", {})
        if "project_json" not in repo:
            continue  # no project.json: the guard already runs on the plugin defaults
        n = json.loads(json.dumps(c))
        n["id"] = PREFIX_W3 + c["id"][len(PREFIX_W2):]
        checks = n["given"]["repo"]["project_json"].setdefault("checks", {})
        for k in sorted(extra):
            checks[k] = extra[k]
        n["tags"] = [t for t in n.get("tags", []) if t != "REQ-W2-084"] + ["REQ-W3-062"]
        out.append(n)
    return out


def regenerate():
    table = json.loads(TABLE.read_text(encoding="utf-8"))
    base = [c for c in table["cases"] if not c["id"].startswith(PREFIX_W3)]
    table["cases"] = base + wave3_cases(base)
    if W3_NOTE not in table["description"]:
        table["description"] += W3_NOTE
    TABLE.write_text(json.dumps(table, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def codes(env):
    return sorted({e.get("code") for e in env.get("errors") or []})


class Validate(unittest.TestCase):
    """@req REQ-W3-062 — the 4.0 fixtures pass validate --strict under 4.1."""

    def fixtures(self, tmp_root):
        """``[(file, root)]``: the legacy fixtures (validated from a bare project) and every fixture project's
        ``spec.json`` / ``project.json`` (validated from its own root)."""
        legacy = sorted((LEGACY / "spec").glob("*.json")) + sorted((LEGACY / "project").glob("*.json"))
        out = [(f, tmp_root) for f in legacy]
        for base in (_path.FIXTURES_DIR, _path.UNIT_DIR / "fixtures"):
            for f in sorted(base.rglob("docs/spec/**/*.json")):
                if f.name in ("spec.json", "project.json"):
                    out.append((f, Path(str(f).split("/docs/spec/")[0])))
        return out

    def validate(self, line, path, root):
        return run_on_line(line, STATE, "validate", str(path), "--strict", "--root", str(root), "--json")

    def test_REQ_W3_062_nothing_that_passes_under_40_fails_under_41(self):
        passed, regressions = 0, []
        with tempfile.TemporaryDirectory(prefix="karvey-compat-") as tmp:
            root = Path(tmp)
            (root / "docs" / "spec" / "changes").mkdir(parents=True)
            for f, froot in self.fixtures(root):
                rc40, env40 = self.validate("4.0", f, froot)
                rc41, env41 = self.validate("4.1", f, froot)
                new = [c for c in codes(env41) if c not in codes(env40)]
                if rc40 == 0:
                    passed += 1
                if (rc40 == 0 and rc41 != 0) or new:
                    regressions.append("%s: fails under 4.1 on %s" % (f.name, ", ".join(new) or "exit %d" % rc41))
        self.assertGreaterEqual(passed, 5, "too few 4.0 fixtures pass: the replay proves nothing")
        self.assertEqual(regressions, [])

    def test_a_cost_limit_key_passes_with_a_warning(self):
        with tempfile.TemporaryDirectory(prefix="karvey-compat-") as tmp:
            root = Path(tmp)
            (root / "docs" / "spec").mkdir(parents=True)
            src = json.loads((LEGACY / "project" / "trunk.json").read_text(encoding="utf-8"))
            src["judges"] = {"budget": {"usd": 5}}
            p = root / "docs" / "spec" / "project.json"
            p.write_text(json.dumps(src), encoding="utf-8")
            rc, env = self.validate("4.1", p, root)
            self.assertEqual(rc, 0, env)
            self.assertIn("cost.cap_key", [w.get("code") for w in env.get("warnings") or []])


class Lint(unittest.TestCase):
    """@req REQ-W3-062 — the linter over a fixture project passes on the 4.1 line."""

    def test_good_fixture_lints_clean_on_41(self):
        good = _path.UNIT_DIR / "fixtures" / "lint" / "good"
        rc, env = run_on_line("4.1", _path.SCRIPTS_DIR / "lint-plugin.py", "--root", str(good), "--format", "json")
        self.assertEqual(rc, 0, env)


class GuardTables(unittest.TestCase):
    """@req REQ-W3-062 — the guard replays with the Wave 3 rows at their 4.1 defaults are in the compat table."""

    def test_the_compat_table_carries_the_41_replays(self):
        cases = json.loads(TABLE.read_text(encoding="utf-8"))["cases"]
        base = [c for c in cases if not c["id"].startswith(PREFIX_W3)]
        mine = [c for c in cases if c["id"].startswith(PREFIX_W3)]
        self.assertEqual(mine, wave3_cases(base), "compat.json is stale: run python3 %s --write" % Path(__file__).name)
        self.assertGreaterEqual(len(mine), 70)
        for c in mine:
            self.assertEqual(c["expect"]["decision"], "allow", c["id"])
            checks = c["given"]["repo"]["project_json"]["checks"]
            self.assertEqual(checks["sponsor.leak"], "blocking")
            self.assertEqual(checks["loadlist.missing"], "blocking")


if __name__ == "__main__":
    if "--write" in sys.argv:
        regenerate()
        print("compat.json regenerated")
    else:
        unittest.main()
